### ISSUE TITLE
feat: Creating Secrets

### ISSUE THREAD

**Issue by sungsoo** [sungsoo/sungsoo.github.io#7]
## feat: Creating Secrets

Secrets can be consumed using the Kubernetes REST API by applications that know how to call that API directly. However, our goal is to keep applications portable. Not only should they run well in Kubernetes, but they should run, unmodified, on other platforms.

Instead of accessing secrets through the API server, we can use a secrets volume.

### Secrets volumes

Secret data can be exposed to Pods using the secrets volume type. Secrets volumes are managed by the **kubelet** and are created at Pod creation time. Secrets are stored on tmpfs volumes (aka RAM disks), and as such are not written to disk on nodes.
Each data element of a secret is stored in a separate file under the target mount point specified in the volume mount. 
The **kuard-tls** secret contains two data elements: _kuard.crt_ and _kuard.key_. Mounting the **kuard-tls** secrets volume to **/tls** results in the following files:

```
    /tls/kuard.crt
    /tls/kuard.key
```

The Pod manifest in the following YAML example (e.g. kuard-secret.yaml) demonstrates how to declare a secrets volume, which exposes the **kuard-tls** secret to the kuard container under **/tls**.

```
apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
spec:
  containers:
    - name: kuard-tls
      image: gcr.io/kuar-demo/kuard-amd64:blue
      imagePullPolicy: Always
      volumeMounts:
      - name: tls-certs
        mountPath: "/tls"
        readOnly: true
  volumes:
    - name: tls-certs
      secret:
           secretName: kuard-tls
```

Create the kuard-tls Pod using kubectl and observe the log output from the running Pod:

```
$ kubectl apply -f kuard-secret.yaml
```

Connect to the Pod by running:

```
$ kubectl port-forward kuard-tls 8443:8443
```

Now navigate your browser to https://localhost:8443. You should see some invalid certificate warnings as this is a self-signed certificate for _kuard.example.com_. If you navigate past this warning, you should see the **kuard** server hosted via HTTPS. Use the “File system browser” tab to find the certificates on disk.
